import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header/Header";
import Footer from "@/components/header/Fotter";
import SearchBar from "@/components/header/SearchBar";
import { HiOutlineArrowNarrowRight } from "react-icons/hi";
import { MdLocationPin } from "react-icons/md";

export default function Home() {
  return (
    <>
      <Head>
        <title>Find Easy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* TODO: Add favIcon */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <div className="wrapper">
          <Header />
          <div className="main">
            <div className="hero-section">
              <div className="left-col">
                <h1>Beyond the Sale A Lifelong Partnership</h1>
                <p className="sub-heading">
                  Experience stress-free home buying and selling with our
                  professional team. Expert guidance for every step of process.
                </p>
                <SearchBar />
                <SeeListingBtn />
              </div>
              <div className="right-col">
                <div className="card-bg">
                  <div className="product-details">
                    <MdLocationPin size="32" />
                    <div>
                      <p className="card-title">
                        JP Nagar, Bengaluru Karnataka
                      </p>
                      <p className="card-dis">
                        2BHK Starting from <strong>80L</strong>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="service-section">
              <ServiceCard />
              <ServiceCard />
              <ServiceCard />
            </div>
          </div>
          <Footer />
        </div>
      </main>
    </>
  );
}

const ServiceCard = () => {
  return <div className="service-card"></div>;
};

const SeeListingBtn = () => {
  return (
    <div className="see-listing-div">
      <div className="see-listing-btn">See listing</div>
      <HiOutlineArrowNarrowRight size="24" />
    </div>
  );
};
